name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
  branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-MAT-100-COT-1-1-101pong-hodavia.bangbola.git"
  EXECUTABLES: "101pong"
 
jobs:
  check_coding_style
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: check_coding_style
        uses: actions/checkout@v3
      - run: check.sh $(pwd) $(pwd)

check_program_compilation      
  runs-on: ubuntu-latest
  container:  epitechcontent/epitest-docker
  timeout-minutes: 2
  steps:
    - name: check_program_compilation
      uses: actions/checkout@v3
    - run: make
    - name: Clean
      uses: actions/checkout@v3
    - run: make clean
 
run_tests
        runs-on: ubuntu-latest
        container: epitechcontent/epitest-docker
        timeout-minutes: 2
        steps:
          - name: run_tests
          uses: actions/checkout@v2
          - name: xc_test
          - run: make run_tests
       
push_to_mirror
       runs-on: ubuntu-latest
       if: github.event_name == 'push'
       steps:
         - name: push_to_mirror
           uses: actions/checkout@v3
         - name: push
         - use: pixta-dev/repository-mirroring-action@v1
         - with:
