name: Chocolatine
env:
  MIRROR_URL : "git@github.com:EpitechPromo2027/B-DOP-200-COT-2-1-chocolatine-espoir.agoli-agbo.git"
  EXECUTABLES : mysh

on:
  push:
    branches-ignore:
      - 'ga-ignore-* '
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_coding_style :
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@v2
          with:
            fetch-depth: 0
      - name: check_for_coding-style
      - run: ghcr.io/epitech/coding-style-checker:latest
      - name: Exit if needed
        if: ${{ env.action_state == 'true' }}
        run:
            exit 1
        continue-on-error: false

  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: make_test
        uses: actions/checkout@v3
      - run: make
        timeout-minutes: 1
      - name: make_clean_test
        uses: actions/checkout@v3
      - run: make clean

  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    needs: [check_program_compilation]
    steps:
      - name: run_tests
        uses: actions/checkout@v3
      - run:
          make test run
        timeout-minutes: 2

  push_to_mirror:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    needs: [check_program_compilation, run_tests]
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: pixta-dev/repository-mirroring-action@v1
          with:
            target_repo_url:
                ${{ env.MIRROR_URL }}
            ssh_private_key:
                ${{ secrets.GIT_SSH_PRIVATE_KEY }}
