name: Chocolatine

env:
  MIRROR_URL: git@github.com:godlynjr/heaven.git
  EXECUTABLES: libmy.a

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    env:
      SHERLOCKED: ${{ secrets.SHERLOCKED }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run coding style checker
        run: check.sh $(pwd) $(pwd) ${{ env.SHERLOCKED }}
        continue-on-error: true
      - name: Display errors
        run: |
          ERRORS=$(find . -type f -name ".c" -o -name ".h" -exec grep -n -H -E -e "^.:[[:space:]][[:graph:]]+[[:space:]]*$" {} \;)
          if [ -n "$ERRORS" ]; then
            echo "$ERRORS" | awk -F: '{printf "::error file=%s,line=%d::%s\n", $1, $2, $3}'
            exit 1
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 3
    env:
      SHERLOCKED: ${{ secrets.SHERLOCKED }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build code
        run: make
      - name: Clean build
        run: make clean
        
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker
    timeout-minutes: 3
    env:
      SHERLOCKED: ${{ secrets.SHERLOCKED }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: make tests_run

  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}