name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
      branches-ignore:
      - 'ga-ignore-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: step1
      uses: actions/checkout@v3
    - run: |
        echo The nameof the repo is $GITHUB_REF
        du -skh --exclude=".git"
 
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - name: make_test
      uses: actions/checkout@v3
    - run: make
      timeout-minutes: 1
    - run: make clean
    - run: |
            if [[ -e $EXECUTABLES ]] && [[ -x $EXECUTABLES ]]
            then
              exit 0
            else
                exit 1
            fi
  check_coding_style:
   runs-on: ubuntu-latest
   container:
      image: ghcr.io/epitech/coding-style-checker:latest
   steps:
    - name: check_coding_style
      uses: actions/checkout@v3
    - run: |
        check.sh $(pwd) $(pwd)
        cat coding-style-reports.log
        if [[ -s $coding-style-reports.log ]]
          done < "coding-style-reports.log"
        exit 1
        fi

