name: Chocolatine

on:
  push:
    branches-ignore: [ ga-ignore-* ]
  pull_request:
    branches-ignore:  [ ga-ignore-* ]

env:
  MIRROR_URL: "https://epitech.bj/"
  EXECUTABLES:  "lem_in"

jobs:
    build:
      runs-on:  ubuntu-latest
      steps:
      - name: checkout Branche
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.head_ref }}
      - name: Job1
        if: success()
        run: echo "Job1"
    check_coding_style:
      runs-on:  ubuntu-latest
      container: ghcr.io/epitech/coding-style-checker:latest
      steps:
      - name: Run coding style
        run:  check.sh $(pwd) $(pwd)
    check_program_compilation:
      runs-on:  ubuntu-latest
      container: epitechcontent/epitest-docker
      steps:
      - name: Run make
        run: echo "make"
        timeout-minutes: 2
       
      - name: Run clean
        run: echo "make clean"

      - name: Test executables
        run:  |
          if  [ ! -x EXECUTABLES ]
          then
              echo 'EXECUTABLES does not there or not executable'
          fi
    run_tests:
      runs-on:  ubuntu-latest
      container: epitechcontent/epitest-docker
      steps:
      - name: Run test
        run: echo "make tests_run"
        timeout-minutes: 2
    push_to_mirror:
      runs-on:  ubuntu-latest
      if: github.event_name == 'push'
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Mirror repository
          uses: pixta-dev/repository-mirroring-action@v1.0.0
          with:
            source-repository: my-username/my-repo
            destination-repository: my-username/my-mirror-repo
        - name: Setup SSH Key
          uses: webfactory/ssh-agent@v0.4.2
          with:
            ssh-private-key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        - name: Push to mirror
          run: |
            echo "git push $MIRROR_URL"
